export const products = [
    {
        id: 'room-corner-lamp',
        basePrice: 15.99,
        currentPrice: 9.89,
        imgsrc: '/fancyroom.webp',
        alttext: 'fancy room corner lamp',
        title: 'Room Corner Lamp',
    },
    {
        id: 'ball-lamp',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/balllamp.webp',
        alttext: 'ball lamp',
        title: 'Ball Lamp',
    },
    {
        id: 'bike-tail-led',
        basePrice: 19.99,
        currentPrice: 14.89,
        imgsrc: '/biketailled.webp',
        alttext: 'bike tail lamp',
        title: 'Bike Tail LED',
    },
    {
        id: 'plastic-carts',
        basePrice: 25.99,
        currentPrice: 19.49,
        imgsrc: '/carts.webp',
        alttext: 'Plastic carts',
        title: 'Plastic Carts',
    },
    {
        id: 'bamboo-mirror',
        basePrice: 21.99,
        currentPrice: 15.79,
        imgsrc: '/canemirror.webp',
        alttext: 'Bamboo mirror',
        title: 'Bamboo Mirror',
    },
    {
        id: 'cloud-neon-light',
        basePrice: 18.99,
        currentPrice: 12.99,
        imgsrc: '/cloudlamp.webp',
        alttext: 'cloud shaped neon light',
        title: 'Cloud Neon Light',
    },
    {
        id: 'coffee-clamp-spoon',
        basePrice: 8.99,
        currentPrice: 5.99,
        imgsrc: '/coffeeclampspoon.webp',
        alttext: 'coffee clamp spoon',
        title: 'Coffee Clamp Spoon',
    },
    {
        id: 'coffee-mug',
        basePrice: 9.99,
        currentPrice: 6.49,
        imgsrc: '/coffeemug.webp',
        alttext: 'coffeemug',
        title: 'Coffee Mug',
    },
    {
        id: 'hanging-lamp',
        basePrice: 22.99,
        currentPrice: 16.49,
        imgsrc: '/hanginglamp.webp',
        alttext: 'hanging lamp',
        title: 'Hanging Lamp',
    },
    {
        id: 'fancy-keychain',
        basePrice: 6.99,
        currentPrice: 4.49,
        imgsrc: '/keychain.webp',
        alttext: 'fancy keychain',
        title: 'Fancy Keychain',
    },
    {
        id: 'full-hd-monitor',
        basePrice: 159.99,
        currentPrice: 139.49,
        imgsrc: '/monitor.webp',
        alttext: 'Full HD monitor',
        title: 'Full HD Monitor',
    },
    {
        id: 'hanging-neon-lights',
        basePrice: 28.99,
        currentPrice: 21.49,
        imgsrc: '/neonlights.webp',
        alttext: 'hanging neon lights',
        title: 'Hanging Neon Lights',
    },
    {
        id: 'orange-headphone',
        basePrice: 32.99,
        currentPrice: 27.49,
        imgsrc: '/orangeheadphone.webp',
        alttext: 'Orange Headphone',
        title: 'Orange Headphone',
    },
    {
        id: 'small-plants',
        basePrice: 5.99,
        currentPrice: 3.99,
        imgsrc: '/plants.webp',
        alttext: 'small plants',
        title: 'Small Plants',
    },
    {
        id: 'cup-with-straw',
        basePrice: 7.99,
        currentPrice: 5.49,
        imgsrc: '/strawcup.webp',
        alttext: 'Cup with Straw',
        title: 'Cup with Straw',
    },
    {
        id: 'round-table-lamp',
        basePrice: 16.99,
        currentPrice: 11.49,
        imgsrc: '/tablelamp.webp',
        alttext: 'Round table lamp',
        title: 'Round Table Lamp',
    },
    {
        id: 'thermo-bottle',
        basePrice: 14.99,
        currentPrice: 9.49,
        imgsrc: '/thermbottle.webp',
        alttext: 'Thermo Bottle',
        title: 'Thermo Bottle',
    },
    {
        id: 'fingerprint-lock',
        basePrice: 29.99,
        currentPrice: 24.49,
        imgsrc: '/touchlock.webp',
        alttext: 'fingerprint lock',
        title: 'Fingerprint Lock',
    },
    {
        id: 'white-ceramic-vase',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/whitevase.webp',
        alttext: 'White Ceramic Vase',
        title: 'White Ceramic Vase',
    },
    {
        id: 'wireless-charge-lamp',
        basePrice: 26.99,
        currentPrice: 19.49,
        imgsrc: '/wirelesschargelamp.webp',
        alttext: 'wireless charge lamp',
        title: 'Wireless Charge Lamp',
    },
    {
        id: 'room-corner-lamp',
        basePrice: 15.99,
        currentPrice: 9.89,
        imgsrc: '/fancyroom.webp',
        alttext: 'fancy room corner lamp',
        title: 'Room Corner Lamp',
    },
    {
        id: 'ball-lamp',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/balllamp.webp',
        alttext: 'ball lamp',
        title: 'Ball Lamp',
    },
    {
        id: 'bike-tail-led',
        basePrice: 19.99,
        currentPrice: 14.89,
        imgsrc: '/biketailled.webp',
        alttext: 'bike tail lamp',
        title: 'Bike Tail LED',
    },
    {
        id: 'plastic-carts',
        basePrice: 25.99,
        currentPrice: 19.49,
        imgsrc: '/carts.webp',
        alttext: 'Plastic carts',
        title: 'Plastic Carts',
    },
    {
        id: 'bamboo-mirror',
        basePrice: 21.99,
        currentPrice: 15.79,
        imgsrc: '/canemirror.webp',
        alttext: 'Bamboo mirror',
        title: 'Bamboo Mirror',
    },
    {
        id: 'cloud-neon-light',
        basePrice: 18.99,
        currentPrice: 12.99,
        imgsrc: '/cloudlamp.webp',
        alttext: 'cloud shaped neon light',
        title: 'Cloud Neon Light',
    },
    {
        id: 'coffee-clamp-spoon',
        basePrice: 8.99,
        currentPrice: 5.99,
        imgsrc: '/coffeeclampspoon.webp',
        alttext: 'coffee clamp spoon',
        title: 'Coffee Clamp Spoon',
    },
    {
        id: 'coffee-mug',
        basePrice: 9.99,
        currentPrice: 6.49,
        imgsrc: '/coffeemug.webp',
        alttext: 'coffeemug',
        title: 'Coffee Mug',
    },
    {
        id: 'hanging-lamp',
        basePrice: 22.99,
        currentPrice: 16.49,
        imgsrc: '/hanginglamp.webp',
        alttext: 'hanging lamp',
        title: 'Hanging Lamp',
    },
    {
        id: 'fancy-keychain',
        basePrice: 6.99,
        currentPrice: 4.49,
        imgsrc: '/keychain.webp',
        alttext: 'fancy keychain',
        title: 'Fancy Keychain',
    },
    {
        id: 'full-hd-monitor',
        basePrice: 159.99,
        currentPrice: 139.49,
        imgsrc: '/monitor.webp',
        alttext: 'Full HD monitor',
        title: 'Full HD Monitor',
    },
    {
        id: 'hanging-neon-lights',
        basePrice: 28.99,
        currentPrice: 21.49,
        imgsrc: '/neonlights.webp',
        alttext: 'hanging neon lights',
        title: 'Hanging Neon Lights',
    },
    {
        id: 'orange-headphone',
        basePrice: 32.99,
        currentPrice: 27.49,
        imgsrc: '/orangeheadphone.webp',
        alttext: 'Orange Headphone',
        title: 'Orange Headphone',
    },
    {
        id: 'small-plants',
        basePrice: 5.99,
        currentPrice: 3.99,
        imgsrc: '/plants.webp',
        alttext: 'small plants',
        title: 'Small Plants',
    },
    {
        id: 'cup-with-straw',
        basePrice: 7.99,
        currentPrice: 5.49,
        imgsrc: '/strawcup.webp',
        alttext: 'Cup with Straw',
        title: 'Cup with Straw',
    },
    {
        id: 'round-table-lamp',
        basePrice: 16.99,
        currentPrice: 11.49,
        imgsrc: '/tablelamp.webp',
        alttext: 'Round table lamp',
        title: 'Round Table Lamp',
    },
    {
        id: 'thermo-bottle',
        basePrice: 14.99,
        currentPrice: 9.49,
        imgsrc: '/thermbottle.webp',
        alttext: 'Thermo Bottle',
        title: 'Thermo Bottle',
    },
    {
        id: 'fingerprint-lock',
        basePrice: 29.99,
        currentPrice: 24.49,
        imgsrc: '/touchlock.webp',
        alttext: 'fingerprint lock',
        title: 'Fingerprint Lock',
    },
    {
        id: 'white-ceramic-vase',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/whitevase.webp',
        alttext: 'White Ceramic Vase',
        title: 'White Ceramic Vase',
    },
    {
        id: 'wireless-charge-lamp',
        basePrice: 26.99,
        currentPrice: 19.49,
        imgsrc: '/wirelesschargelamp.webp',
        alttext: 'wireless charge lamp',
        title: 'Wireless Charge Lamp',
    },
    {
        id: 'room-corner-lamp',
        basePrice: 15.99,
        currentPrice: 9.89,
        imgsrc: '/fancyroom.webp',
        alttext: 'fancy room corner lamp',
        title: 'Room Corner Lamp',
    },
    {
        id: 'ball-lamp',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/balllamp.webp',
        alttext: 'ball lamp',
        title: 'Ball Lamp',
    },
    {
        id: 'bike-tail-led',
        basePrice: 19.99,
        currentPrice: 14.89,
        imgsrc: '/biketailled.webp',
        alttext: 'bike tail lamp',
        title: 'Bike Tail LED',
    },
    {
        id: 'plastic-carts',
        basePrice: 25.99,
        currentPrice: 19.49,
        imgsrc: '/carts.webp',
        alttext: 'Plastic carts',
        title: 'Plastic Carts',
    },
    {
        id: 'bamboo-mirror',
        basePrice: 21.99,
        currentPrice: 15.79,
        imgsrc: '/canemirror.webp',
        alttext: 'Bamboo mirror',
        title: 'Bamboo Mirror',
    },
    {
        id: 'cloud-neon-light',
        basePrice: 18.99,
        currentPrice: 12.99,
        imgsrc: '/cloudlamp.webp',
        alttext: 'cloud shaped neon light',
        title: 'Cloud Neon Light',
    },
    {
        id: 'coffee-clamp-spoon',
        basePrice: 8.99,
        currentPrice: 5.99,
        imgsrc: '/coffeeclampspoon.webp',
        alttext: 'coffee clamp spoon',
        title: 'Coffee Clamp Spoon',
    },
    {
        id: 'coffee-mug',
        basePrice: 9.99,
        currentPrice: 6.49,
        imgsrc: '/coffeemug.webp',
        alttext: 'coffeemug',
        title: 'Coffee Mug',
    },
    {
        id: 'hanging-lamp',
        basePrice: 22.99,
        currentPrice: 16.49,
        imgsrc: '/hanginglamp.webp',
        alttext: 'hanging lamp',
        title: 'Hanging Lamp',
    },
    {
        id: 'fancy-keychain',
        basePrice: 6.99,
        currentPrice: 4.49,
        imgsrc: '/keychain.webp',
        alttext: 'fancy keychain',
        title: 'Fancy Keychain',
    },
    {
        id: 'full-hd-monitor',
        basePrice: 159.99,
        currentPrice: 139.49,
        imgsrc: '/monitor.webp',
        alttext: 'Full HD monitor',
        title: 'Full HD Monitor',
    },
    {
        id: 'hanging-neon-lights',
        basePrice: 28.99,
        currentPrice: 21.49,
        imgsrc: '/neonlights.webp',
        alttext: 'hanging neon lights',
        title: 'Hanging Neon Lights',
    },
    {
        id: 'orange-headphone',
        basePrice: 32.99,
        currentPrice: 27.49,
        imgsrc: '/orangeheadphone.webp',
        alttext: 'Orange Headphone',
        title: 'Orange Headphone',
    },
    {
        id: 'small-plants',
        basePrice: 5.99,
        currentPrice: 3.99,
        imgsrc: '/plants.webp',
        alttext: 'small plants',
        title: 'Small Plants',
    },
    {
        id: 'cup-with-straw',
        basePrice: 7.99,
        currentPrice: 5.49,
        imgsrc: '/strawcup.webp',
        alttext: 'Cup with Straw',
        title: 'Cup with Straw',
    },
    {
        id: 'round-table-lamp',
        basePrice: 16.99,
        currentPrice: 11.49,
        imgsrc: '/tablelamp.webp',
        alttext: 'Round table lamp',
        title: 'Round Table Lamp',
    },
    {
        id: 'thermo-bottle',
        basePrice: 14.99,
        currentPrice: 9.49,
        imgsrc: '/thermbottle.webp',
        alttext: 'Thermo Bottle',
        title: 'Thermo Bottle',
    },
    {
        id: 'fingerprint-lock',
        basePrice: 29.99,
        currentPrice: 24.49,
        imgsrc: '/touchlock.webp',
        alttext: 'fingerprint lock',
        title: 'Fingerprint Lock',
    },
    {
        id: 'white-ceramic-vase',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/whitevase.webp',
        alttext: 'White Ceramic Vase',
        title: 'White Ceramic Vase',
    },
    {
        id: 'wireless-charge-lamp',
        basePrice: 26.99,
        currentPrice: 19.49,
        imgsrc: '/wirelesschargelamp.webp',
        alttext: 'wireless charge lamp',
        title: 'Wireless Charge Lamp',
    },
    {
        id: 'room-corner-lamp',
        basePrice: 15.99,
        currentPrice: 9.89,
        imgsrc: '/fancyroom.webp',
        alttext: 'fancy room corner lamp',
        title: 'Room Corner Lamp',
    },
    {
        id: 'ball-lamp',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/balllamp.webp',
        alttext: 'ball lamp',
        title: 'Ball Lamp',
    },
    {
        id: 'bike-tail-led',
        basePrice: 19.99,
        currentPrice: 14.89,
        imgsrc: '/biketailled.webp',
        alttext: 'bike tail lamp',
        title: 'Bike Tail LED',
    },
    {
        id: 'plastic-carts',
        basePrice: 25.99,
        currentPrice: 19.49,
        imgsrc: '/carts.webp',
        alttext: 'Plastic carts',
        title: 'Plastic Carts',
    },
    {
        id: 'bamboo-mirror',
        basePrice: 21.99,
        currentPrice: 15.79,
        imgsrc: '/canemirror.webp',
        alttext: 'Bamboo mirror',
        title: 'Bamboo Mirror',
    },
    {
        id: 'cloud-neon-light',
        basePrice: 18.99,
        currentPrice: 12.99,
        imgsrc: '/cloudlamp.webp',
        alttext: 'cloud shaped neon light',
        title: 'Cloud Neon Light',
    },
    {
        id: 'coffee-clamp-spoon',
        basePrice: 8.99,
        currentPrice: 5.99,
        imgsrc: '/coffeeclampspoon.webp',
        alttext: 'coffee clamp spoon',
        title: 'Coffee Clamp Spoon',
    },
    {
        id: 'coffee-mug',
        basePrice: 9.99,
        currentPrice: 6.49,
        imgsrc: '/coffeemug.webp',
        alttext: 'coffeemug',
        title: 'Coffee Mug',
    },
    {
        id: 'hanging-lamp',
        basePrice: 22.99,
        currentPrice: 16.49,
        imgsrc: '/hanginglamp.webp',
        alttext: 'hanging lamp',
        title: 'Hanging Lamp',
    },
    {
        id: 'fancy-keychain',
        basePrice: 6.99,
        currentPrice: 4.49,
        imgsrc: '/keychain.webp',
        alttext: 'fancy keychain',
        title: 'Fancy Keychain',
    },
    {
        id: 'full-hd-monitor',
        basePrice: 159.99,
        currentPrice: 139.49,
        imgsrc: '/monitor.webp',
        alttext: 'Full HD monitor',
        title: 'Full HD Monitor',
    },
    {
        id: 'hanging-neon-lights',
        basePrice: 28.99,
        currentPrice: 21.49,
        imgsrc: '/neonlights.webp',
        alttext: 'hanging neon lights',
        title: 'Hanging Neon Lights',
    },
    {
        id: 'orange-headphone',
        basePrice: 32.99,
        currentPrice: 27.49,
        imgsrc: '/orangeheadphone.webp',
        alttext: 'Orange Headphone',
        title: 'Orange Headphone',
    },
    {
        id: 'small-plants',
        basePrice: 5.99,
        currentPrice: 3.99,
        imgsrc: '/plants.webp',
        alttext: 'small plants',
        title: 'Small Plants',
    },
    {
        id: 'cup-with-straw',
        basePrice: 7.99,
        currentPrice: 5.49,
        imgsrc: '/strawcup.webp',
        alttext: 'Cup with Straw',
        title: 'Cup with Straw',
    },
    {
        id: 'round-table-lamp',
        basePrice: 16.99,
        currentPrice: 11.49,
        imgsrc: '/tablelamp.webp',
        alttext: 'Round table lamp',
        title: 'Round Table Lamp',
    },
    {
        id: 'thermo-bottle',
        basePrice: 14.99,
        currentPrice: 9.49,
        imgsrc: '/thermbottle.webp',
        alttext: 'Thermo Bottle',
        title: 'Thermo Bottle',
    },
    {
        id: 'fingerprint-lock',
        basePrice: 29.99,
        currentPrice: 24.49,
        imgsrc: '/touchlock.webp',
        alttext: 'fingerprint lock',
        title: 'Fingerprint Lock',
    },
    {
        id: 'white-ceramic-vase',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/whitevase.webp',
        alttext: 'White Ceramic Vase',
        title: 'White Ceramic Vase',
    },
    {
        id: 'wireless-charge-lamp',
        basePrice: 26.99,
        currentPrice: 19.49,
        imgsrc: '/wirelesschargelamp.webp',
        alttext: 'wireless charge lamp',
        title: 'Wireless Charge Lamp',
    },
    {
        id: 'room-corner-lamp',
        basePrice: 15.99,
        currentPrice: 9.89,
        imgsrc: '/fancyroom.webp',
        alttext: 'fancy room corner lamp',
        title: 'Room Corner Lamp',
    },
    {
        id: 'ball-lamp',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/balllamp.webp',
        alttext: 'ball lamp',
        title: 'Ball Lamp',
    },
    {
        id: 'bike-tail-led',
        basePrice: 19.99,
        currentPrice: 14.89,
        imgsrc: '/biketailled.webp',
        alttext: 'bike tail lamp',
        title: 'Bike Tail LED',
    },
    {
        id: 'plastic-carts',
        basePrice: 25.99,
        currentPrice: 19.49,
        imgsrc: '/carts.webp',
        alttext: 'Plastic carts',
        title: 'Plastic Carts',
    },
    {
        id: 'bamboo-mirror',
        basePrice: 21.99,
        currentPrice: 15.79,
        imgsrc: '/canemirror.webp',
        alttext: 'Bamboo mirror',
        title: 'Bamboo Mirror',
    },
    {
        id: 'cloud-neon-light',
        basePrice: 18.99,
        currentPrice: 12.99,
        imgsrc: '/cloudlamp.webp',
        alttext: 'cloud shaped neon light',
        title: 'Cloud Neon Light',
    },
    {
        id: 'coffee-clamp-spoon',
        basePrice: 8.99,
        currentPrice: 5.99,
        imgsrc: '/coffeeclampspoon.webp',
        alttext: 'coffee clamp spoon',
        title: 'Coffee Clamp Spoon',
    },
    {
        id: 'coffee-mug',
        basePrice: 9.99,
        currentPrice: 6.49,
        imgsrc: '/coffeemug.webp',
        alttext: 'coffeemug',
        title: 'Coffee Mug',
    },
    {
        id: 'hanging-lamp',
        basePrice: 22.99,
        currentPrice: 16.49,
        imgsrc: '/hanginglamp.webp',
        alttext: 'hanging lamp',
        title: 'Hanging Lamp',
    },
    {
        id: 'fancy-keychain',
        basePrice: 6.99,
        currentPrice: 4.49,
        imgsrc: '/keychain.webp',
        alttext: 'fancy keychain',
        title: 'Fancy Keychain',
    },
    {
        id: 'full-hd-monitor',
        basePrice: 159.99,
        currentPrice: 139.49,
        imgsrc: '/monitor.webp',
        alttext: 'Full HD monitor',
        title: 'Full HD Monitor',
    },
    {
        id: 'hanging-neon-lights',
        basePrice: 28.99,
        currentPrice: 21.49,
        imgsrc: '/neonlights.webp',
        alttext: 'hanging neon lights',
        title: 'Hanging Neon Lights',
    },
    {
        id: 'orange-headphone',
        basePrice: 32.99,
        currentPrice: 27.49,
        imgsrc: '/orangeheadphone.webp',
        alttext: 'Orange Headphone',
        title: 'Orange Headphone',
    },
    {
        id: 'small-plants',
        basePrice: 5.99,
        currentPrice: 3.99,
        imgsrc: '/plants.webp',
        alttext: 'small plants',
        title: 'Small Plants',
    },
    {
        id: 'cup-with-straw',
        basePrice: 7.99,
        currentPrice: 5.49,
        imgsrc: '/strawcup.webp',
        alttext: 'Cup with Straw',
        title: 'Cup with Straw',
    },
    {
        id: 'round-table-lamp',
        basePrice: 16.99,
        currentPrice: 11.49,
        imgsrc: '/tablelamp.webp',
        alttext: 'Round table lamp',
        title: 'Round Table Lamp',
    },
    {
        id: 'thermo-bottle',
        basePrice: 14.99,
        currentPrice: 9.49,
        imgsrc: '/thermbottle.webp',
        alttext: 'Thermo Bottle',
        title: 'Thermo Bottle',
    },
    {
        id: 'fingerprint-lock',
        basePrice: 29.99,
        currentPrice: 24.49,
        imgsrc: '/touchlock.webp',
        alttext: 'fingerprint lock',
        title: 'Fingerprint Lock',
    },
    {
        id: 'white-ceramic-vase',
        basePrice: 12.99,
        currentPrice: 8.49,
        imgsrc: '/whitevase.webp',
        alttext: 'White Ceramic Vase',
        title: 'White Ceramic Vase',
    },
    {
        id: 'wireless-charge-lamp',
        basePrice: 26.99,
        currentPrice: 19.49,
        imgsrc: '/wirelesschargelamp.webp',
        alttext: 'wireless charge lamp',
        title: 'Wireless Charge Lamp',
    },
];